"use strict";
function continuityValues(pkg){const f=pkg.facts||{};return{currentStatus:f.currentProject?`${f.currentProject.id}: ${f.currentProject.status}`:null,nextStep:f.currentTasks?.length?f.currentTasks.map(x=>x.id).join(", "):f.nextPhase||null};}
function continuityNarrative(f){return `O projeto atual e ${f.currentProject?.id||"nao informado"} - ${f.currentProject?.name||"sem nome"} (${f.currentProject?.status||"sem status"}). A fase atual e ${f.currentPhase?.id||"nao informada"}. Projetos pausados: ${(f.pausedProjects||[]).map(x=>x.id).join(", ")||"nenhum"}. Tarefas atuais: ${(f.currentTasks||[]).map(x=>x.id).join(", ")||"nenhuma"}. A proxima fase e ${f.nextPhase||"nao informada"}.`;}
function fallback(pkg){const f=pkg.facts||{};let answer="";let currentStatus=null,nextStep=null,technicalRecommendation=null;
 if(pkg.intent==="editorial_operation"){currentStatus="Rascunhos D1 operacionais; MDX permanece como projecao publica atual";nextStep="Validar o fluxo local e permanecer Aguardando Git para Git, push e Cloudflare manuais";answer=`Fluxo atual pelo painel:
1. Rascunho D1 permite criar, salvar, recuperar e editar conteudo real.
2. Para gerar MDX local, use uma acao administrativa explicita; content/posts/ usa UTF-8 sem BOM e nao permite sobrescrita.
3. Gere catalogo local em acao separada com lock, timeout e rollback, reutilizando scripts/generate-posts.js; lib/generated-posts.ts e derivado.
4. Valide public/images/, /blog e builds. O estado final local e Aguardando Git.
5. Git, push e Cloudflare permanecem manuais. MDX permanece como projecao publica atual; D1 ainda nao substitui diretamente a fonte publica MDX e nao existe dupla escrita permanente.
6. A autoria padrao e Greyce e o piloto tecnico fica fora da producao.

Fluxo TXT preservado:
7. Preserve content/inbox/SLUG.txt e public/images/NOME.ext.
8. Use scripts/import-article.js; o importador preserva frontmatter e cria .mdx.backup.
9. Valide e execute scripts/generate-posts.js para atualizar lib/generated-posts.ts.`;}
 else if(pkg.intent==="project_continuity"){const v=continuityValues(pkg);currentStatus=v.currentStatus;nextStep=v.nextStep;answer=continuityNarrative(f);}
 else if(pkg.intent==="product_roadmap"){currentStatus=f.currentEpic?`${f.currentEpic.name}: ${f.currentEpic.status}`:null;nextStep=f.nextEpic?.name||null;technicalRecommendation=f.technicalRecommendation||null;answer=`O epico atual e ${f.currentEpic?.name||"nao informado"} (${f.currentEpic?.status||"sem status"}). O proximo epico planejado e ${nextStep||"nao informado"}. A recomendacao tecnica atual e ${technicalRecommendation||"nao informada"}.`;}
 else if(pkg.intent==="context_engine_roadmap"){currentStatus=(f.current||[]).map(x=>x.name).join(", ")||null;nextStep=f.next?.name||null;answer=`A evolucao atual do Context Engine e ${currentStatus||"nao informada"}. A proxima etapa planejada e ${nextStep||"nao informada"}.`;}
 else if(pkg.intent==="technical_risk"){answer=`Saude arquitetural: ${f.architectureHealth?.score??"n/a"}/100 (${f.architectureHealth?.status||"sem status"}). Dividas abertas: ${(f.openDebts||[]).map(x=>`${x.id}: ${x.reason}`).join("; ")||"nenhuma"}.`;}
 else if(pkg.intent==="architecture_decision"){answer=`Decisoes arquiteturais ativas: ${(f.decisions||[]).map(x=>`${x.id}: ${x.title}`).join("; ")||"nenhuma"}.`;}
 else{answer=(f.chunks||[]).length?`Fontes mais relevantes: ${f.chunks.map(x=>`${x.sourcePath}:${x.startLine}-${x.endLine}`).join("; ")}.`:"Nenhuma fonte relevante foi encontrada.";}
 return{intent:pkg.intent,answer,currentStatus,nextStep,technicalRecommendation,sources:pkg.sources,warnings:[...pkg.warnings,"Resposta deterministica: Ollama indisponivel ou resposta invalida"]};}
function validateAnswer(value,pkg){if(!value||typeof value!=="object")throw new Error("Answer must be an object");if(value.intent!==pkg.intent)throw new Error("Answer intent mismatch");if(typeof value.answer!=="string"||!value.answer.trim())throw new Error("Answer text missing");if(!Array.isArray(value.sources)||!value.sources.length)throw new Error("Answer sources missing");const allowed=new Set(pkg.sources);if(value.sources.some(s=>!allowed.has(s)))throw new Error("Answer contains untrusted source");if(!Array.isArray(value.warnings))throw new Error("Answer warnings missing");
 const contracts={project_continuity:{fields:["currentStatus","nextStep"],sources:pkg.sources},product_roadmap:{fields:["currentStatus","nextStep","technicalRecommendation"],sources:["project-map.json#contextEngine.projectStatus","project-map.json#contextEngine.roadmap","project-map.json#aiContext.recommendedAction"]},context_engine_roadmap:{fields:["currentStatus","nextStep"],sources:["project-map.json#contextEngine.technicalRoadmap"]},technical_risk:{fields:[],sources:["project-map.json#architectureHealth","project-map.json#technicalDebt"]},architecture_decision:{fields:[],sources:["project-map.json#contextEngine.architectureDecisions"]},editorial_operation:{fields:["currentStatus","nextStep"],sources:pkg.sources},code_search:{fields:[],sources:pkg.sources}};
 const contract=contracts[pkg.intent];if(!contract)throw new Error("Unsupported answer intent contract");for(const field of contract.fields){if(typeof value[field]!=="string"||!value[field].trim())throw new Error(`Required field missing for ${pkg.intent}: ${field}`);}for(const source of contract.sources){if(!value.sources.includes(source))throw new Error(`Required source missing for ${pkg.intent}: ${source}`);}
 if(pkg.intent==="editorial_operation"){for(const token of ["Rascunho D1","gerar MDX local","catalogo local","Aguardando Git","content/inbox/","public/images/","content/posts/","UTF-8 sem BOM","scripts/import-article.js",".mdx.backup","scripts/generate-posts.js","lib/generated-posts.ts","/blog","Greyce","Git","Cloudflare","projecao publica atual","dupla escrita permanente"]){if(!value.answer.includes(token))throw new Error(`Editorial operation answer missing canonical token: ${token}`);}for(const obsolete of ["D1 ainda nao esta implementado","D1 permanece futura","painel permanece sem gravacao"]){if(value.answer.includes(obsolete))throw new Error(`Editorial operation answer contains obsolete premise: ${obsolete}`);}}
 if(pkg.intent==="project_continuity"){const f=pkg.facts||{};const expected=continuityValues(pkg);if(value.currentStatus!==expected.currentStatus)throw new Error("Project continuity currentStatus mismatch");if(value.nextStep!==expected.nextStep)throw new Error("Project continuity nextStep mismatch");for(const token of [f.currentProject?.id,f.currentPhase?.id,...(f.pausedProjects||[]).map(x=>x.id),...(f.currentTasks||[]).map(x=>x.id),f.nextPhase].filter(Boolean)){if(!value.answer.includes(token))throw new Error(`Project continuity answer missing canonical token: ${token}`);}}
 return value;}
module.exports={fallback,validateAnswer};
