"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const {NORMALIZATION_WARNING,compareSources,composeModelAnswer}=require("../compose-model-answer");const {validateAnswer}=require("../contextual-answer");
const pkg={intent:"code_search",sources:["a","b","app/blog/categoria/[categoria]/page.tsx:34-71"],facts:{chunks:[]},warnings:[]};
function answer(overrides={}){return{intent:"code_search",answer:"Analise valida",sources:[...pkg.sources],warnings:[],...overrides};}
test("composes all canonical sources when model returns one",()=>{const r=composeModelAnswer(answer({sources:["a"]}),pkg);assert.deepEqual(r.sources,pkg.sources);assert.ok(r.warnings.includes(NORMALIZATION_WARNING));assert.equal(validateAnswer(r,pkg),r);});
test("composes canonical sources when model omits sources",()=>{const original={intent:"code_search",answer:"Analise valida",warnings:[]};const r=composeModelAnswer(original,pkg);assert.deepEqual(r.sources,pkg.sources);assert.ok(r.warnings.includes(NORMALIZATION_WARNING));});
test("discards untrusted model sources without propagating their value",()=>{const r=composeModelAnswer(answer({sources:["invented"]}),pkg);assert.deepEqual(r.sources,pkg.sources);assert.ok(!JSON.stringify(r).includes("invented"));});
test("does not warn when sources already match exactly",()=>{const r=composeModelAnswer(answer(),pkg);assert.deepEqual(r.warnings,[]);assert.deepEqual(r.sources,pkg.sources);});
test("preserves canonical source order",()=>{const r=composeModelAnswer(answer({sources:[...pkg.sources].reverse()}),pkg);assert.deepEqual(r.sources,pkg.sources);assert.ok(r.warnings.includes(NORMALIZATION_WARNING));});
test("does not mutate model answer or context package",()=>{const model=answer({sources:["a"],warnings:["existing"]});const modelSnapshot=JSON.stringify(model);const pkgSnapshot=JSON.stringify(pkg);const r=composeModelAnswer(model,pkg);assert.equal(JSON.stringify(model),modelSnapshot);assert.equal(JSON.stringify(pkg),pkgSnapshot);assert.notEqual(r.sources,pkg.sources);assert.notEqual(r.warnings,model.warnings);});
test("source comparison preserves bracket paths",()=>{const d=compareSources(pkg.sources,["a"]);assert.deepEqual(d.missing,["b","app/blog/categoria/[categoria]/page.tsx:34-71"]);assert.deepEqual(d.untrusted,[]);});
test("wrong intent remains rejected",()=>{const r=composeModelAnswer(answer({intent:"technical_risk"}),pkg);assert.throws(()=>validateAnswer(r,pkg),/intent mismatch/);});
test("empty answer remains rejected",()=>{const r=composeModelAnswer(answer({answer:""}),pkg);assert.throws(()=>validateAnswer(r,pkg),/Answer text missing/);});
test("missing required fields remain rejected for product roadmap",()=>{const p={intent:"product_roadmap",sources:["project-map.json#contextEngine.projectStatus","project-map.json#contextEngine.roadmap","project-map.json#aiContext.recommendedAction"],facts:{},warnings:[]};const r=composeModelAnswer({intent:"product_roadmap",answer:"x",sources:[],warnings:[]},p);assert.throws(()=>validateAnswer(r,p),/Required field missing/);});
