"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const {buildContextPackage}=require("../context-package");const {fallback,validateAnswer}=require("../contextual-answer");
const projects={projects:[{id:"EPIC-003",name:"Site",status:"paused",pendingWork:["X"]},{id:"EPIC-004",name:"Editorial",status:"paused",pendingWork:["Y"]},{id:"EPIC-HARNESS-001",name:"Harness",status:"in_progress",ownedCapabilities:["Z"]}]};const plan={currentPhase:"PHASE-HARNESS-00-TRANSITION",nextPhase:"PHASE-ANCHOR-01-INVENTORY",phases:[{id:"PHASE-HARNESS-00-TRANSITION",name:"Transition",status:"in_progress",deliverables:["many"],acceptanceCriteria:["many"],tasks:[{id:"TASK-HARNESS-TRANSITION-CLEANUP",title:"Cleanup",status:"in_progress",deliverables:["many"]}]}]};const memory={decisions:Array.from({length:5},(_,i)=>({id:`DEC-${i}`,title:"Long title",category:"governance",status:"active",impacts:["many"]}))};const rules={rules:Array.from({length:14},(_,i)=>({id:`RULE-${i}`,title:"Long title",scope:"rag",status:"active",statement:"many"}))};const conflicts={summary:{open:0}};
function pkg(){return buildContextPackage({question:"estado",intent:"project_continuity",map:{},index:{chunks:[]},projects,plan,planPath:"site-context/registry/plans/PLAN-ANCHOR-MVP.json",memory,rules,conflicts});}
test("compacts project continuity facts",()=>{const p=pkg();assert.equal(p.facts.activeDecisionCount,5);assert.equal(p.facts.activeRuleCount,14);assert.equal(p.facts.activeDecisions,undefined);assert.equal(p.facts.activeRules,undefined);assert.equal(p.facts.currentProject.pendingWork,undefined);assert.ok(Buffer.byteLength(JSON.stringify(p))<1800);});
test("accepts exact canonical continuity answer",()=>{const p=pkg();const a=fallback(p);assert.equal(validateAnswer(a,p),a);});
test("rejects wrong continuity next step",()=>{const p=pkg();const a={...fallback(p),warnings:[],nextStep:"PHASE-HARNESS-00-TRANSITION"};assert.throws(()=>validateAnswer(a,p),/nextStep mismatch/);});
test("rejects incomplete continuity status",()=>{const p=pkg();const a={...fallback(p),warnings:[],currentStatus:"in_progress"};assert.throws(()=>validateAnswer(a,p),/currentStatus mismatch/);});
test("rejects narrative missing canonical paused projects",()=>{const p=pkg();const a={...fallback(p),warnings:[],answer:"EPIC-HARNESS-001 PHASE-HARNESS-00-TRANSITION TASK-HARNESS-TRANSITION-CLEANUP PHASE-ANCHOR-01-INVENTORY"};assert.throws(()=>validateAnswer(a,p),/EPIC-003/);});
