"use server";
import { redirect } from "next/navigation";
import { hasValidAdminSession } from "@/lib/cms/admin-session";
import { getCmsDatabase } from "@/lib/cms/cloudflare-context";
import { createDraft, findDraftById, updateDraft } from "@/lib/cms/draft-repository";
import { validateDraftInput, type DraftErrors } from "@/lib/cms/draft";
import { generateLocalMdx } from "@/lib/cms/local-mdx-publisher";
import { generateLocalCatalog } from "@/lib/cms/local-catalog-generator";
export type DraftActionState={errors?:DraftErrors;formError?:string};const raw=(formData:FormData)=>Object.fromEntries(formData.entries());
export async function saveNewDraft(_:DraftActionState,formData:FormData):Promise<DraftActionState>{if(!(await hasValidAdminSession()))redirect("/admin/login");const parsed=validateDraftInput(raw(formData));if(!parsed.ok)return{errors:parsed.errors};let draft;try{draft=await createDraft(getCmsDatabase(),parsed.value);}catch(error){return{formError:error instanceof Error?error.message:"Não foi possível salvar o rascunho."};}redirect(`/admin/rascunhos/${draft.id}/editar`);}
export async function saveExistingDraft(id:string,_:DraftActionState,formData:FormData):Promise<DraftActionState>{if(!(await hasValidAdminSession()))redirect("/admin/login");const parsed=validateDraftInput(raw(formData));if(!parsed.ok)return{errors:parsed.errors};try{await updateDraft(getCmsDatabase(),id,parsed.value);}catch(error){return{formError:error instanceof Error?error.message:"Não foi possível atualizar o rascunho."};}redirect(`/admin/rascunhos/${id}/editar`);}
export async function generateLocalArticle(id:string):Promise<void>{if(!(await hasValidAdminSession()))redirect("/admin/login");let query;try{const draft=await findDraftById(getCmsDatabase(),id);if(!draft)throw new Error("Rascunho não encontrado.");const parsed=validateDraftInput(draft);if(!parsed.ok)throw new Error("O rascunho possui campos inválidos.");const result=generateLocalMdx(parsed.value);query=`mdx=success&path=${encodeURIComponent(result.relativePath)}`;}catch(error){query=`mdx=error&message=${encodeURIComponent(error instanceof Error?error.message:"Não foi possível gerar o artigo local.")}`;}redirect(`/admin/rascunhos/${id}/editar?${query}`);}
export async function generateCatalogForDraft(id:string):Promise<void>{if(!(await hasValidAdminSession()))redirect("/admin/login");let query;try{const draft=await findDraftById(getCmsDatabase(),id);if(!draft)throw new Error("Rascunho não encontrado.");const result=await generateLocalCatalog(draft.slug);query=`catalog=success&before=${result.previousCount}&after=${result.currentCount}&slug=${encodeURIComponent(result.slug)}`;}catch(error){query=`catalog=error&message=${encodeURIComponent(error instanceof Error?error.message:"Não foi possível gerar o catálogo local.")}`;}redirect(`/admin/rascunhos/${id}/editar?${query}`);}
