import type { DraftInput, DraftRecord } from "./draft";
export type D1Result = { success: boolean; meta?: { changes?: number } };
export type D1Statement = { bind(...values: unknown[]): D1Statement; run(): Promise<D1Result>; first<T>(): Promise<T | null>; all<T>(): Promise<{ results: T[] }> };
export type CmsDatabase = { prepare(query: string): D1Statement };
const row = (x: any): DraftRecord => ({ id:x.id,slug:x.slug,title:x.title,description:x.description,category:x.category,content:x.content,author:x.author,image:x.image,status:"draft",createdAt:x.created_at,updatedAt:x.updated_at });
export class DuplicateDraftSlugError extends Error { constructor(){super("Já existe um rascunho com este slug.");} }
export async function createDraft(db:CmsDatabase,input:DraftInput,now=new Date(),id=crypto.randomUUID()):Promise<DraftRecord>{
  const iso=now.toISOString(); try { const result=await db.prepare("INSERT INTO cms_drafts (id,slug,title,description,category,content,author,image,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,'draft',?,?)").bind(id,input.slug,input.title,input.description,input.category,input.content,input.author??null,input.image??null,iso,iso).run(); if(!result.success) throw new Error("Não foi possível salvar o rascunho."); } catch(e){ if(String(e).toLowerCase().includes("unique")) throw new DuplicateDraftSlugError(); throw e; } const found=await findDraftById(db,id); if(!found) throw new Error("Rascunho salvo, mas não localizado."); return found;
}
export async function findDraftById(db:CmsDatabase,id:string){const value=await db.prepare("SELECT * FROM cms_drafts WHERE id = ? AND status = 'draft'").bind(id).first<any>();return value?row(value):null;}
export async function updateDraft(db:CmsDatabase,id:string,input:DraftInput,now=new Date()):Promise<DraftRecord>{const iso=now.toISOString();try{const result=await db.prepare("UPDATE cms_drafts SET slug=?,title=?,description=?,category=?,content=?,author=?,image=?,updated_at=? WHERE id=? AND status='draft'").bind(input.slug,input.title,input.description,input.category,input.content,input.author??null,input.image??null,iso,id).run();if(!result.success||!result.meta?.changes)throw new Error("Rascunho não encontrado.");}catch(e){if(String(e).toLowerCase().includes("unique"))throw new DuplicateDraftSlugError();throw e;}const found=await findDraftById(db,id);if(!found)throw new Error("Rascunho atualizado, mas não localizado.");return found;}
export async function listDrafts(db:CmsDatabase){const result=await db.prepare("SELECT * FROM cms_drafts WHERE status='draft' ORDER BY updated_at DESC").all<any>();return result.results.map(row);}